name: '@askraja'
favicon: null
layout_spectrum: 0.7576
typography_spectrum: 0.50475
title: hello_w0rld by @askraja
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9330649
  lightness: 0
  saturation: 0.4441461
  rhythmicContrast: 0.2142857
purpose: []
