collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0
color:
  saturation: 0
  brandStrength: 0.9330649
  lightness: 0.6825994
  rhythmicContrast: 0
layout_spectrum: 0.8555392
name: '@askraja'
